name: Execute Calculator.exe

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Calculator.exe
      run: |
        cd demo
        chmod +x Calculator.exe
        ./Calculator.exe

