name: Execute Exe File

on:
  push:
    branches:
      - main  # Adjust this branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run .exe File
      run: |
        chmod +x Calculator.exe  # Make the .exe file executable (Linux)
        ./your-exe-file.exe         # Run the .exe file

