name: Execute .exe File

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build
      run: |
        choco install dotnetcore-sdk --yes --version=3.1.201
        dotnet build --configuration Release
        dotnet test --configuration Release --collect "Code coverage"

    - name: Execute .exe
      run: .\Calculator.exe



# name: Execute .exe File
# on:
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: windows-latest
#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v2

#     - name: Execute .exe
#       run: .\Calculator.exe
