name: Build and Run .exe

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.1' # Specify your desired Python version

    - name: Run .exe file
      run: |
        # Assuming your .exe file is in the project directory
        cd demo/Calculator.exe
        ./Calculator.exe
